# Site settings
title:          雷烈
description:    "博士生活的碎碎念，记录科研的日常。"
url:            https://github.com/luwin1127/luwin1127.github.io
# Author
author:
  name:         Lei Lie
  email:        lordofdapanji@foxmail
  url:          https://github.com/luwin1127/luwin1127.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: lordofdapanji@foxmail.com
  github: luwin1127

# The RSS link  
rss: "leilie.top/feed.xml"

# The followings are settings for displays of your blog.
theme_setting:
  # Every default value in the following settings is false. You can set them globally here or separately in a single post/page/chapter.
  code: true # Code highlight.
  math: true # Mathjax
  #  Locales of this theme.
  lang:
    category_all: Blogs # The first tag in the categories bar on the blog layout page. By clicking it all of your posts will be shown. Default is 'All'.
    blog_title: 返回 # The text of ← back url on the top of the post layout.  Default is 'Home'.